version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
  build:
    commands:
      - echo Build started on `date`
      - sudo npm install
  post_build:
    commands:
      - echo build completed
      - sudo pm2 start npm start src/index.js -- start
artifacts:
  files:
    - appspec.yml
    - script/
    - node_modules/
    - '**/*'
